In [11]:
import pandas as pd 
import numpy as np 

# getting namUs Database
missing_db_1 = pd.read_csv("./created databases/ready-search-missing-person.csv")

missing_db_1.head()

,Case Number,DLC,Legal Last Name,Legal First Name,Missing Age,City,County,State,Biological Sex,Date Modified,Race Category
0,MP128712,09/04/2024,Campirano,Nixon,16.0,Goodyear,Maricopa,AZ,Male,09/06/2024,White / Caucasian
1,MP128606,08/31/2024,Batra,Anjali,18.0,Morgan Hill,Santa Clara,CA,Female,09/04/2024,Mix / Other / Unknown
2,MP128466,08/30/2024,CLARK,JOSHUA,35.0,Mulberry,Polk,FL,Male,09/06/2024,White / Caucasian
3,MP128454,08/30/2024,Turney-Long,Alinda,16.0,Winter Haven,Polk,FL,Female,09/06/2024,White / Caucasian
4,MP128473,08/30/2024,COTE,KATHY,78.0,West Palm Beach,Palm Beach,FL,Female,09/06/2024,White / Caucasian

In [12]:
# last contacted input 
dlc = input("When was the last time you had contact/last seen loved one? MM/DD/YYYY : ")
# which state last seen input 
state = input("What state was your loved one last seen/known to be in?: ")
# age of when went missing 
age = input("What was the age of your loved one when first missing?: ")

def findSimilarCases(dlc, state, age): 

    # year of missing 
    dlc = dlc.split("/")[2]

    # gets cases in db that have same year as input year 
    similar_dlc_year = missing_db_1[missing_db_1["DLC"].str.split("/").str[2].fillna("") == dlc]

    # gets cases in db that have same year and state input 
    similar_dlc_state = similar_dlc_year[similar_dlc_year["State"] == state]

    # gets cases in db that have same year, state, and age input 
    similar_dlc_state.loc[:, 'Missing Age'] = pd.to_numeric(similar_dlc_state.loc[:, 'Missing Age'], errors='coerce')
    similar_dlc_state_age = similar_dlc_state[similar_dlc_state['Missing Age'] == pd.to_numeric(age)]

    # print cases that have same input values
    print(similar_dlc_state_age)

findSimilarCases(dlc, state, age)

    Case Number         DLC Legal Last Name Legal First Name  Missing Age  \
1      MP128606  08/31/2024           Batra           Anjali         18.0
167    MP125557  07/10/2024        Castillo             Noah         18.0

               City          County State Biological Sex Date Modified  \
1       Morgan Hill     Santa Clara    CA         Female    09/04/2024
167  San Bernardino  San Bernardino    CA           Male    07/29/2024

             Race Category
1    Mix / Other / Unknown
167  Mix / Other / Unknown